# Generated by Django 3.1.7 on 2021-02-26 20:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import round.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('contestant_id', models.IntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(200000), django.core.validators.MaxValueValidator(999999)], verbose_name='Contestant ID')),
                ('contestant_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['contestant_id'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('number', models.IntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('prompt', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallback_number', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(2000000), django.core.validators.MaxValueValidator(9999999)])),
                ('solution', models.FileField(max_length=140, upload_to=round.models.contestant_problem_path)),
                ('submission_time', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('DNA', 'Not Attempted'), ('ATT', 'Attempted'), ('MKD', 'Marked')], default='DNA', max_length=3)),
                ('contestant', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='round.contestant')),
                ('problem', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='round.problem')),
            ],
            options={
                'ordering': ['contestant', 'problem'],
                'permissions': [('submit_solutions', 'Can submit solutions'), ('mark_solutions', 'Can mark solutions')],
            },
        ),
    ]
