# Generated by Django 3.2.7 on 2021-10-10 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
